In [2]:
# -*- coding: utf-8 -*-
from __future__ import print_function
import torch

In [3]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = torch.add(x, 2)
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [5]:
y.grad_fn

In [6]:
z = y**2 * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [10]:
a = torch.randn(2, 2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad=True
b = (a**2).sum()
b.grad_fn

False


In [11]:
out.backward()

In [12]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

## Generally speaking, torch.autograd is an engine for computing vector-Jacobian product.

In [13]:
x = torch.randn(3, requires_grad=True)
y = x*2
while y.data.norm() < 100:
    y = y * 2
y

tensor([109.1390, -11.4218,  58.6590], grad_fn=<MulBackward0>)

In [14]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
x.grad

tensor([1.2800e+01, 1.2800e+02, 1.2800e-02])

In [16]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [15]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
