In [3]:
# -*- coding: utf-8 -*-
from __future__ import print_function
import torch

In [4]:
x = torch.empty(5, 3)
x

tensor([[-8.9258e+08,  4.5827e-41, -8.9258e+08],
        [ 4.5827e-41,  6.7421e+22,  1.3556e-19],
        [ 1.8037e+28,  2.1040e-19,  1.8515e+28],
        [ 1.7744e+28,  5.3831e-14,  1.8037e+28],
        [ 6.7120e+22,  2.8231e+23,  7.1377e+31]])

In [5]:
x = torch.rand(5, 3)
x

tensor([[0.8746, 0.4134, 0.2107],
        [0.0822, 0.1558, 0.7411],
        [0.8631, 0.2812, 0.7100],
        [0.2259, 0.5853, 0.1143],
        [0.9667, 0.2408, 0.3567]])

In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [7]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [8]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [11]:
x = torch.rand_like(x, dtype=torch.float)
x

tensor([[0.2713, 0.0320, 0.0770],
        [0.7581, 0.4989, 0.9658],
        [0.6667, 0.8354, 0.1706],
        [0.8344, 0.9590, 0.5670],
        [0.4553, 0.4129, 0.2177]])

In [12]:
x.size()

torch.Size([5, 3])

In [13]:
y = torch.rand(5, 3)
torch.add(x, y)

tensor([[0.5277, 0.1924, 0.5711],
        [0.9272, 0.9772, 1.0484],
        [1.1787, 1.6743, 0.9130],
        [0.9751, 1.2618, 1.2342],
        [0.8470, 0.5903, 0.4338]])

In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[0.5277, 0.1924, 0.5711],
        [0.9272, 0.9772, 1.0484],
        [1.1787, 1.6743, 0.9130],
        [0.9751, 1.2618, 1.2342],
        [0.8470, 0.5903, 0.4338]])

In [15]:
y.add_(x)
y

tensor([[0.5277, 0.1924, 0.5711],
        [0.9272, 0.9772, 1.0484],
        [1.1787, 1.6743, 0.9130],
        [0.9751, 1.2618, 1.2342],
        [0.8470, 0.5903, 0.4338]])

In [16]:
x[:,1]

tensor([0.0320, 0.4989, 0.8354, 0.9590, 0.4129])

In [17]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
x = torch.randn(1)
x.item()

-0.06974377483129501

In [19]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [20]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [24]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))